config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	root "home#top"

	root "users#index"

	get "home/about" => "home#about"

	post "like/:id" => "likes#like", as: "like"
  	delete "like/:id" => "likes#unlike", as: "unlike"

	post "follow/:id" => "relationships#follow", as: "follow"
  	post "unfollow/:id" => "relationships#unfollow", as: "unfollow"

  	resources :users, only: [:show, :edit, :update]

  	resources :relationships, only: [:follow, :unfollow]

	resources :shops do
		resource :likes, only: [:like, :unlike]
		resources :shop_comments, only: [:create, :destroy]
	end

	resources :users do
		member do
			get "goodbye"
			patch "bye"
			get :following, :followers
		end
	end

end

app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user
	belongs_to :shop
	# User、Shopモデルに対してbelongs_toの関連付け
	# likeは1対NのN側(userに対して複数存在する)

	validates :user_id, presence: true
	validates :shop_id, presence: true

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	before_action :authenticate_user!
	before_action :shop_params
	# ログイン済ユーザーのみにアクセスを許可する

	def like
		like = Like.create(user_id: current_user.id, shop_id: @shop.id)
		redirect_back(fallback_location: root_path)
		# 他の画面に遷移せずLikeを行う
	end

	def unlike
		like = Like.find_by(user_id: current_user.id, shop_id: @shop.id).destroy
		redirect_back(fallback_location: root_path)
		# 他の画面に遷移せずUnlikeを行う
	end

	private

	def shop_params
		@shop = Shop.find(params[:id])
	end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if current_user.liked_by?(shop.id) %>
	<%= link_to unlike_path(shop), method: :delete, remote: true  do %>
		<i class="fas fa-heart"> <%= shop.likes.count %></i>
	<% end %>
<% else %>
	<%= link_to like_path(shop), method: :post, remote: true do %>
		<i class="far fa-heart"> <%= shop.likes.count %></i>
	<% end %>
<% end %>

app/views/likes/create.js.erb
$(".shop_<%= @shop.id %>").html("<%= j(render 'likes/like',  shop: @shop ) %>")

app/views/likes/destroy.js.erb
$(".shop_<%= @shop.id %>").html("<%= j(render 'likes/like',  shop: @shop ) %>")