config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	root "home#top"

	root "users#index"

	get "home/about" => "home#about"

	post "like/:id" => "likes#like", as: "like"
  	delete "like/:id" => "likes#unlike", as: "unlike"

	post "follow/:id" => "relationships#follow", as: "follow"
  	post "unfollow/:id" => "relationships#unfollow", as: "unfollow"

  	resources :users, only: [:show, :edit, :update]

  	resources :relationships, only: [:follow, :unfollow]

	resources :shops do
		resource :likes, only: [:like, :unlike]
		resources :shop_comments, only: [:create, :destroy]
	end

	resources :users do
		member do
			get "goodbye"
			patch "bye"
			get :following, :followers
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :shops, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :shop_comments, dependent: :destroy
	# userは1対Nの1側(複数のNを所持する)
	# class userが削除された際は上記も削除される(dependent: :destroy)

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  # フォローを取得する
  # フォロワーを取得する
  # 自分がフォローしている人を取得する
  # 自分をフォローしている人を取得する

  enum is_active: {Available: true, Invalid: false}
  # 有効会員はtrue、退会済み会員はfalse

  attachment :profile_image, destroy: false

  def liked_by?(shop_id)
    likes.where(shop_id: shop_id).exists?
  end

  def active_for_authentication?
    super && (self.is_active == "Available")
  end
  # is_activeが有効の場合は有効会員(ログイン可能)

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!
	# ログイン済ユーザーのみにアクセスを許可する

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@shops = @user.shops
		# @userに紐付く@shops
	end

	def following
		@user  = User.find(params[:id])
		@users = @user.follower
		render "follow"
	end

	def followers
		@user  = User.find(params[:id])
		@users = @user.followed
		render 'follower'
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find_by(id: params[:id])
		@user.update(user_params)
		if
			@user.save
			redirect_to user_path(@user.id)
			# @userがsaveされた場合、編集後のuserにpath
		else
			render action: :edit
			# 上記以外の場合、編集画面に戻る
		end
	end

	def goodbye
		@user = User.find(params[:id])
	end

	def bye
		@user = User.find(current_user.id)
		@user.update(is_active: "Invalid")
		@user.destroy
		reset_session
		redirect_to root_path
		# ユーザーを退会済みにupdate
	end

	private

	def user_params
		params.require(:user).permit(:active, :name, :introduction, :profile_image)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_followbutton.html.erb
<% if current_user.following?(user) %>
	<%= link_to "Unfollow", unfollow_path(user.id), method: :post, remote: true %>
<% else %>
	<%= link_to "Follow", follow_path(user.id), method: :post, remote: true %>
<% end %>

app/views/users/edit.html.erb
<div class="container" align="center">

	<div class="top">
		<h1>Edit Profile</h1>
	</div>

	<%= form_for @user do |f| %>
		<div class="grad">
	    	<div class="login">
	    		<div class="field">
				    <%= f.label "Name" %>
				    <%= f.text_field :name %>
				</div>
				<div class="field">
				    <%= f.label "Introduction" %>
				    <%= f.text_field :introduction %>
				</div>
	  		</div>
	  	</div>

		<div class="profile-image">
	  		<%= f.label "Profile Image" %>
			<%= f.attachment_field :profile_image, fallback: "no_image.jpg" %>
		</div>

		<div class="done">
	      	<%= f.submit "Done", :class => "button" %>
	  	</div>
	<% end %>

</div>

app/views/users/follow.html.erb
<div class="container" align="center">

	<table class="user_index">
		<% @user.following_user.each do |user| %>
			<tr>
				<td>
					<%= link_to user_path(user) do %>
						<%= attachment_image_tag user, :profile_image, size:"100x100", fallback: "no_image.jpg" %>
						<%= user.name %>
					<% end %>
				</td>

				<td class="followbutton_<%= user.id %>">
					<% unless user == current_user %>
						<%= render "followbutton", user: user %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>

</div>

app/views/users/follow.js.erb
$("#followbutton_<%= @user.id %>").html("<%= j(render 'users/followbutton', user: @user) %>");

app/views/users/follower.html.erb
<div class="container" align="center">

	<table class="user_index">
		<% @user.follower_user.each do |user| %>
			<tr>
				<td>
					<%= link_to user_path(user) do %>
						<%= attachment_image_tag user, :profile_image, size:"100x100", fallback: "no_image.jpg" %>
						<%= user.name %>
					<% end %>
				</td>

				<td class="followbutton_<%= user.id %>">
					<% unless user == current_user %>
						<%= render "followbutton", user: user %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>

</div>

app/views/users/goodbye.html.erb
<div class="container" align="center">

	<div class="bye">
		<h2>Do you want withdrawal ??</h2>
	</div>
	<div class="bye-link">
		<p><%= link_to "Return Mypage", user_path(current_user.id) %></p>
		<p><%= link_to "Withdrawal", bye_user_path(@user.id), method: :patch %></p>
	</div>

</div>

app/views/users/index.html.erb
<div class="container" align="center">

	<table class="user_index">
		<% if user_signed_in? %>
			<% @users.each do |user| %>
				<% if user.is_active == "Available" %>
					<tr>
						<td>
							<div class="icon_idex">
								<%= link_to user_path(user) do %>
									<%= attachment_image_tag user, :profile_image, size:"50x50", fallback: "no_image.jpg", :class => "icon_index" %>
									<%= user.name %>
								<% end %>
							</div>
						</td>

						<td class="followbutton_<%= user.id %>">
							<% unless user == current_user %>
								<%= render "followbutton", user: user %>
							<% end %>
						</td>
					</tr>
				<% end %>
			<% end %>
		<% end %>
	</table>

</div>

app/views/users/show.html.erb
<div class="container" align="center">

	<div class="icon">
		<%= attachment_image_tag @user, :profile_image, size:"150x150", fallback: "no_image.jpg", :class => "icon" %>
	</div>

	<table class="all-table">
		<tr>
			<th> Follow </th>
			<th> Follower </th>
			<th> Shops </th>
		</tr>

		<tr align="center">
			<td><%=link_to @user.follower.count, following_user_path(@user) %></td>
			<td><%=link_to @user.followed.count, followers_user_path(@user) %></td>
			<td><%=link_to @shops.count %></td>
		</tr>
	</table>

	<% if @user === current_user %>
		<table class="all-table">
			<th><%= link_to "New shops", new_shop_path %> /</th>
			<th><%= link_to "EditProfile", edit_user_path(current_user.id) %> /</th>
			<th><%= link_to "Withdrawal", goodbye_user_path %></th>
		</table>
	<% end %>

	<p>◯ <%= @user.name %></p>
	<p>◯ <%= @user.introduction %></p>

	<div class="followbutton_<%= @user.id %>">
		<% unless @user == current_user %>
			<%= render "followbutton", user: @user %>
		<% end %>
	</div>

	<% @shops.each do |shop| %>
		<div class="col-md-4">
			<div class="set">
				<%= link_to shop_path(shop.id) do %>
					<%= attachment_image_tag shop, :shop_image, size:"300x300", fallback: "no_image.jpg" %></br>
					<%= link_to shop.shop_name, shop_path(shop.id) %>
				<% end %>
			</div>
		</div>
	<% end %>

</div>

app/views/users/unfollow.js.erb
$("#followbutton_<%= @user.id %>").html("<%= j(render 'users/followbutton', user: @user) %>");