config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	root "home#top"

	root "users#index"

	get "home/about" => "home#about"

	post "like/:id" => "likes#like", as: "like"
  	delete "like/:id" => "likes#unlike", as: "unlike"

	post "follow/:id" => "relationships#follow", as: "follow"
  	post "unfollow/:id" => "relationships#unfollow", as: "unfollow"

  	resources :users, only: [:show, :edit, :update]

  	resources :relationships, only: [:follow, :unfollow]

	resources :shops do
		resource :likes, only: [:like, :unlike]
		resources :shop_comments, only: [:create, :destroy]
	end

	resources :users do
		member do
			get "goodbye"
			patch "bye"
			get :following, :followers
		end
	end

end

app/models/shop_comment.rb
class ShopComment < ApplicationRecord

	belongs_to :user
	belongs_to :shop
	# User、Shopモデルに対してbelongs_toの関連付け
	# shop_commentは1対NのN側(userに対して複数存在する)

	validates :comment, presence: true

end

app/controllers/shop_comments_controller.rb
class ShopCommentsController < ApplicationController

	before_action :authenticate_user!
	# ログイン済ユーザーのみにアクセスを許可する

	def create
		shop = Shop.find(params[:shop_id])
		shop_comment = current_user.shop_comments.new(shop_comment_params)
		shop_comment.shop_id = shop.id
		shop_comment.save
		redirect_back(fallback_location: root_path)
		# 他の画面に遷移しない
	end

	def destroy
		ShopComment.find_by(id: params[:id], shop_id: params[:shop_id]).destroy
		redirect_back(fallback_location: root_path)
		# shopcommentを見つけdestroy
		# 他の画面に遷移しない
	end

	private

	def shop_comment_params
		params.require(:shop_comment).permit(:comment)
	end

end

app/helpers/shop_comments_helper.rb
module ShopCommentsHelper
end

app/views/shop_comments/_shop_comment.html.erb
<div class="comment">

	<% @shop_comments.each do |shop_comment| %>
		<table class="c-table">
			<tr>
				<td><%= attachment_image_tag shop_comment.user, :profile_image, size:"50x50", fallback: "no_image.jpg", :class => "icon-mini" %></td>
				<td><%= link_to shop_comment.user.name, user_path(shop_comment.user.id) %></td>
				<td><%= shop_comment.comment %></td>
			<% if shop_comment.user === current_user %>
				<td><%= link_to "Destroy", shop_shop_comment_path(shop_comment.shop, shop_comment), method: :delete, "data-confirm" => "本当に消去しますか？" %></td>
			<% end %>
			</tr>
		</table>
	<% end %>

	<div class="comment-box">
		<%= form_for [@shop, @shop_comment] do |f| %>
			<%= f.text_area :comment, size:"70x5", :placeholder => "Please comment." %>
			<p><%= f.submit "Done", :class => "button-2" %></p>
		<% end %>
	</div>

</div>