config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	root "home#top"

	root "users#index"

	get "home/about" => "home#about"

	post "like/:id" => "likes#like", as: "like"
  	delete "like/:id" => "likes#unlike", as: "unlike"

	post "follow/:id" => "relationships#follow", as: "follow"
  	post "unfollow/:id" => "relationships#unfollow", as: "unfollow"

  	resources :users, only: [:show, :edit, :update]

  	resources :relationships, only: [:follow, :unfollow]

	resources :shops do
		resource :likes, only: [:like, :unlike]
		resources :shop_comments, only: [:create, :destroy]
	end

	resources :users do
		member do
			get "goodbye"
			patch "bye"
			get :following, :followers
		end
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>GATHER COFFEESTAND</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
        <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    </head>

    <body class="background">
        <header class="navbar navbar-expand-lg" align="center">
            <div class="container">
                <nav class="navbar-center">
                    <h3><%=link_to "GATHER COFFEESTAND", root_path %></h3>
                </nav>

                <nav>
                    <a class="nav" align="center">
                        <% if user_signed_in? %>
                            <%= link_to "Top", root_path %>/
                            <%= link_to "About", home_about_path %>/
                            <%= link_to "Shops", shops_path %>/
                            <%= link_to "Users", users_path %>/
                            <%= link_to "Mypage", user_path(current_user.id) %>/
                            <%= link_to "Logout", destroy_user_session_path, method: :delete %>/
                            <div class="search" align="right">
                                <%= form_tag(shops_path, :method => "get") do %>
                                    <%= text_field_tag :search, params[:search], size:"15x1", :placeholder => "Shop search." %>
                                    <%= submit_tag "🔍", :shop_name => nil %>
                                <% end %>
                            </div>
                        <% else %>
                            <%= link_to "Top", root_path %>/
                            <%= link_to "About", home_about_path %>/
                            <%= link_to "Signup", new_user_registration_path %>/
                            <%= link_to "Login", new_user_session_path %>
                        <% end %>
                    </a>
                </nav>
            </div>
        </header>

    <%= yield %>

    <footer>
    　　<ul class="footer-menu" align="center">
            <li><%= link_to "Top", root_path %></li>
            <li>/</li>
            <li><%= link_to "About", home_about_path %></li>
        </ul>
        <p>© All rights reserved by Gather Coffeestand</p>
    </footer>

    </body>
</html>